---
title: "Lab"
---

# What's in the lab?

There are several models or approaches for a lab. Ours will be arrived at collectively, combining the following.  Regardless,  a reproducible write-up is essential.

## The project/activity approach

This includes projects ranging in scope, ambition, and potential, from the weekly or bi-weekly activity to the term-long project.

#### Lab as a series of activities

This is the most traditional approach. Activities are typically smaller in scope than "projects." These particular activities, drawn from Salgarnik's *Bit by Bit,* are focused on computational social science.   

http://www.princeton.edu/~mjs3/soc596_f2016/labs.shtml

#### Lab as a series of projects

Example: Bravo's (Maryland) Introduction to Data Science

Four projects including http://www.hcbravo.org/IntroDataSci/projects/Project2/, http://www.hcbravo.org/IntroDataSci/projects/Project4/.

#### Lab as building to a single, publishable data project

At Harvard, students develop "a month-long data science project. The goal of the project is to go through the complete data science process to answer questions you have about some topic of your own choosing. You will acquire the data, design your visualizations, run statistical analysis, and communicate the results." http://datasciencelabs.github.io/2016/pages/projects.html

At UCSB, there is a working group which produces student projects and publishes them on the https://www.inertia7.com platform

**Any such project would, presumably, be submitted to the Research Symposium**

A more modest, but somewhat cool thing to consider, would be to modify the rBookdown package to create a template for a thesis that would be acceptable here at the Honors College.

## The skills approach

A second approach would be for us to build on skills not considered, or considered only briefly, in the main class.  Examples could include study of Git and GitHub for version control, Jupyter notebooks (roughly, Python:Jupyter as R markdown:R), or SQL and database management.

Within R, students could collectively learn to use other packages (eg., leaflet, igraph) or, conceivably, write their own.

Students might also be interested in developing better visualizations, using other tools including Tableau.

(Other data viz work could be improving on Lanning's old papers - see ...)

**I expect that a critical component of these skills would be writing documentation that would be accessible to me and to students who are taking the lecture but not the lab.**

## The 'my data' approach

A third approach would be to use the tools of data science to examine data that you are examining in someone's lab here at the WHC. This could include data that you will analyze for your thesis if those data are being examined by a group of students in the class.

## The 'other data' approach

Here, we can examine datasets such as those discussed in Seth Stephens-Davidowitz' book - http://sethsd.com/research/.  I think that we should do this either next week or the week after, depending on when students can get the book.

There are a zillion other data sources, too.

## Competitions and challenges

As @hicks2017guide has argued, competitions or challenges are a major feature of contemporary data science, but are underrepresented in teaching in the area. One approach for us would be to examine [Kaggle datasets](https://inclass.kaggle.com/datasets), such as the [Global Terrorism Database](https://inclass.kaggle.com/START-UMD/gtd)

The classic Kaggle is the [Netflix prize](https://gist.github.com/loretoparisi/be046926960797a15fea).

## All or some of the above

We can combine some or all of these, depending on the goals of the class.  That's what we will begin to examine today.

#### Be patient. Remeber that trying can be trying

# Where do I find data?

In 2018, "finding data" is kind of like "looking for air" (e.g., there's a lot of it, and some samples of air are better than others).  Data are everywhere, the question is what to look at and, as discussed in the first class, what *not* to look at too.

Part of the assignment for the next lab is to pitch an idea for a data set or data problem to examine to your classmates.  This will be 5 minutes or less, a simple oral talk that begins with **"I think we should study..."** It doesn't have to be perfect. The important thing is for you to spend some time looking at data and thinking about it.  

I spent a few minutes looking through the list of datasets on the [www.kaggle.com/datasets](http://www.kaggle.com/datasets) page.  The main goal of a kaggle competition is to use machine learning techniques to come up with a better way to predict an outcome of interest.  This is too far advanced for us right now (but will be accessible at the end of the class if you choose).  But looking through their datasets is really interesting. 

### A sample pitch

On Kaggle, there is, a challenge for predicting housing prices using data from Zillow.  This includes a lot of data on housing prices, including data on historical trends by zip code and the health of the market here in Jupiter. (Jupiter is, relative to other local markets, a better place to sell than buy a home right now. As you know from class, I am in the middle of doing both of these at this writing). If you are interested in this stuff, all of the Zillow data can be found at <https://www.zillow.com/research/data/>. And for the podcast people, there is an interview with an analyst from Zillow on Data Skeptic here <https://dataskeptic.com/blog/episodes/2017/zillow-zestimate>. 

**If you Google "housing prices r" **you can see a number of examples of how people examine, predict, and report housing prices.  Some of this may look challenging, but you (particularly as a team) will be able to adapt code like this for your own use in the weeks ahead. 

#### Beyond Zillow

If I were pitching something (and I'm not - this is just an example), I might ask the following: **Have areas that voted for Trump increased in value more than those which went for Clinton since last November?**  To address this, we would need to combine the Zillow data with some regional data on voting.  Could we do this? Should we, and do we want to?

## Working collaboratively

As we discussed in class, there are two parts to the assignment this week.  The first is to look for and pitch an interesting dataset or data project. I'll discuss this in another post.   The other is to contribute to this post to collectively answer this question (Chapter 2, activity 7) from the Salgarnik book.  **How far can we get with this? How can each student contribute to the solution**? Here's the question: [http://www.bitbybitbook.com/en/observing-behavior/observing-activities](http://www.bitbybitbook.com/en/observing-behavior/observing-activities/). 

The source paper (Michel 2011) is in our Slack channel. Using this or other materials, contribute to a shared post on our Slack channel.

# Moving forward

For our latest assignments, etc., see our Slack channel.

