---
title: "Topic list"
---

The class will cover a series of modules, each of which may be covered in more than or less than a single class period.

## Introduction

1 Data science for the liberal arts

2 Pretest

3 Setting up your computer

4 Some basic tools: Slack, Markdown, Google Docs

5 An introduction to R 

6 Finding help

## Towards data literacy

7 Empiricism > intuition

8 The ubiquity of data

9 Counting and observing

10 Principles of data visualization 

11 Probability

12 Inference

13 Reproducibility

## Towards data proficiency

14 Literate programming with R markdown 

15 Data visualization in R with ggplot2

16 Exploratory Data Analysis

17 Tidy data and the tidyverse

18 Messy data: Cleaning and curation

19 Selecting data in R with dplyr

20 Manipulating data in R with dplyr

21 Working with relational data

22 Working with strings, factors, dates, and times

23 Working with lists 

24 Open science

## Towards data fluency

25 Writing functions

26 Writing loops

27 Getting data: Web scraping and APIs 

28 Linear and multiple regression

29 Logistic regression

30 Classification and types of errors

31 Cross-validation

32 Some machine learning techniques

33 Analyzing text data

34 Analyzing networks 

35 Categories and classification

36 Making interactive visualizations with R Shiny

## Towards data leadership

37 The significance of scalability 

38 Digital humanities and data science

39 Humility and teamwork

40 Ethics and data responsibility

